### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by ricksbrown**
Pretty self explanatory PR.

### CODE REVIEW

**Comment by klown** [comment]
Thanks @ricksbrown !

For future reference:  The documents in the w3c/aria repository have different editors, where each editor is responsible for their document(s).  As the editor of core-aam.html, I have merged only your core-aam changes from this pull request.  FYI, the commit is here:
https://github.com/w3c/aria/commit/41feb626ad049245efee96cd90de91982d23ea93

In future, please make separate pull requests for different documents/editors.

Thanks again.

**Comment by ricksbrown** [comment]
@klown roger that, will bear that in mind in future. :smile:

**Comment by Joanmarie** [comment]
I'm not the maintainer/editor of graphics2.html, but the maintainer/editor just blessed your changes. So I manually merged the rest in commit 5a70ca8e. Thanks again!

**Comment by Joanmarie** [comment]
Sorry to be spammy. @ricksbrown: If we've addressed all the issues, please close it.

**Pull request closed without merging**
