### PR TITLE
ARIA-PRACTICES in SpecRef

### PR DESCRIPTION
**Pull request by marcoscaceres**
- http://www.specref.org/?q=ARIA-PRACTICES

### CODE REVIEW

**Comment by MichielBijl** [comment]
In related news, I have filed a PR to specref to update APG ED: https://github.com/tobie/specref/pull/284

**Comment by marcoscaceres** [comment]
Woot! Thank you!

**Comment by MichielBijl** [comment]
In more related news, that was closed. But it will be auto updated next time we publish a WD to TR.

**Comment by joanmarie** [comment]
Thanks for the pull request. Merge issues aside, we cannot merely remove that entry because the entries in SpecRef are all "wai" prefixed, and a couple of the specs in this repo cite the unprefixed version that you're removing, namely [Graphics AAM](https://github.com/w3c/aria/blob/master/graphics-aam/graphics-aam.html#L292) and [SVG AAM](https://github.com/w3c/aria/blob/master/svg-aam/svg-aam.html#L367). I could go in and fix those, but as a general rule we don't make changes to specs for which we are not editor. I'm not an editor of those specs. @richschwer or @AmeliaBR?

**Comment by joanmarie** [comment]
I did a new pull request (#616) fixing the aforementioned specs which would be broken by this pull request, and then removing the local entry (conflict resolved). So closing this PR as a duplicate of #616.

**Pull request closed without merging**
