### PR TITLE
fix link to menu button example

### PR DESCRIPTION
**Pull request by a11ydoer**
please add a link to new menu button example

### CODE REVIEW

**Comment by MichielBijl** [comment]
Can you add the space back in line 192 (`omment archive</a>) or<a href="https:/`)?

And can you remove the title attribute from the link (`title="Menubutton" target="_blank">Menu button</a>`)?

**Comment by a11ydoer** [comment]
I think I just copied other example link, which has title and target attribute(ie. link). Is not the way Spec done?

**Comment by MichielBijl** [comment]
Yeah those need to go too, but we'll fix that after the heartbeat publication; I'll make an issue for it.

**Comment by jnurthen** [comment]
Seeing as there is still a change to make here can you please close it and resubmit against Master with just the change to the menu link.
Thanks.

**Pull request closed without merging**
