### PR TITLE
Initial aria-textseparation (depends on generic PR being merged)

### PR DESCRIPTION
**Pull request by carmacleod**
Separated `aria-textseparation` attribute definition from `generic` role definition.
This PR depends on https://github.com/w3c/aria/pull/805 being merged first.
This markup contains inline comments describing what would need to be manually merged.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 20, 2021, 10:59 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Faria%2F3b0182354d6553c914fe1c1b853d7f6f9cfe940c%2Findex.html%3FisPreview%3Dtrue)

```
waiting for function failed: timeout 30000ms exceeded
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/aria%23996.)._
</details>

### CODE REVIEW

**Comment by carmacleod** [comment]
For discussion: Which of the 4 categories in the [Taxonomy of WAI-ARIA States and Properties](file:///C:/Users/CAROLYNMacLeod/git/aria/index.html#state_prop_taxonomy) should `aria-textseparation` go into: Widget, Live Region, Drag-and-Drop, or Relationship Attributes? (maybe Relationship?).

**Comment by carmacleod** [comment]
@jnurthen Should this be labelled as 1.3?

**Comment by pkra** [comment]
#805 has been merged. 

@carmacleod who should review this one?

**Comment by carmacleod** [comment]
@pkra Wow, this is an old one. :)
The whole group needs to decide whether or not we still want this.

**Pull request closed without merging**
