### PR TITLE
revise role=presentation example

### LINKED ISSUE #1647: Question: role presentation on non-semantic elements - why?
In the ARIA 1.2 Spec for  [Role Presentation](https://www.w3.org/TR/wai-aria-1.2/#presentation) [Example 9](https://www.w3.org/TR/wai-aria-1.2/#example-9) has the following example:
`
<span role="presentation"> Sample Content </span>`
 
I am finding a lot of seemingly unnecessary uses of role presentation/none on non-semantic elements in the wild and when accessibility testing. The '_Depending on styling and other factors_' has no further explanation as to why styling or factors would require this role.

I have read that the Role Presentation/None can be used as a bug fix, but can't remember what it fixes.
 
I'd appreciate your opinion on this.

### PR DESCRIPTION
**Pull request by scottaohara**
closes #1647

- removes examples which are unclear without including notes about some current AT behaviors.
- updates reference to the fact that a `span` is a type of `generic`.
- some minor editorial updates to surrounding content

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/1699.html" title="Last updated on Mar 5, 2022, 12:13 AM UTC (7225167)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1699/c577b84...7225167.html" title="Last updated on Mar 5, 2022, 12:13 AM UTC (7225167)">Diff</a>

### CODE REVIEW

**Review by chlane — APPROVED** [review]
I think this will help authors better understand the behavior of role=presentation

**Review by Jaunita-George — APPROVED** [review]
Great job!!

**Review by MelSumner — APPROVED** [review]
👍  Improves it! :shipit:

**Review by Jaunita-George — COMMENTED** [review]
Looks good!

**Pull request merged**
