### PR TITLE
Changed logic to preserve referenced items.

### PR DESCRIPTION
**Pull request by halindrome**
New logic that is smart about terms that reference other terms.  This resolves the broken links that were introduced via the merge of pull request #110

### CODE REVIEW

**Comment by Joanmarie** [comment]
Since I hadn't been following the #109 + #110 discussion, I started with a diff of glossary terms that are present as a result of this fix:

    --- before	2015-12-16 20:34:51.909841211 +0100
    +++ after	2015-12-16 20:39:13.606577300 +0100
    @@ -2,8 +2,11 @@
     
     accessibility api
      accessibility apis
     +accessibility tree
     +accessible description
      accessible name
      accessible names
     +accessible object
      accessible objects
      assistive technologies
      assistive technology
     @@ -28,6 +31,7 @@
      managed state
      managed states
      nemeth braille
     +node
      normative
      object
      objects
     @@ -51,6 +55,7 @@
      state
      states
      taxonomy
     +text node
      understandable
      user agent
      user agents

Seems harmless to me, and hopefully fixes the issue @michael-n-cooper reported.

I'm guessing node or text node are referenced in other specs we manage? (If not, I'm not convinced it's a big deal -- read "worth the apparent hassle")

**Comment by Joanmarie** [comment]
Ok, so one verifiable example of something that is broken in master but fixed in the branch associated with this issue is the inclusion of Accessible Description in the glossary. Accessible Description is referenced by Accessible Name's glossary entry, and Accessible Name is referenced in the spec. Thus both Accessible Name and Accessible Description belong in the spec.

@halindrome Since @michael-n-cooper is the one who experienced the breakage, I think it would make sense for him to verify if all of his issues have been addressed and nothing else regressed as a result of your proposed change.

**Comment by halindrome** [comment]
Works for me!

On Wed, Dec 16, 2015 at 3:56 PM, Joanmarie <notifications@github.com> wrote:

> Ok, so one verifiable example of something that is broken in master but
> fixed in the branch associated with this issue is the inclusion of
> Accessible Description in the glossary. Accessible Description is
> referenced by Accessible Name's glossary entry, and Accessible Name is
> referenced in the spec. Thus both Accessible Name and Accessible
> Description belong in the spec.
>
> @halindrome <https://github.com/halindrome> Since @michael-n-cooper
> <https://github.com/michael-n-cooper> is the one who experienced the
> breakage, I think it would make sense for him to verify if all of his
> issues have been addressed and nothing else regressed as a result of your
> proposed change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/aria/pull/112#issuecomment-165256534>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
Uggh - I apparently broke the merge by checking in the fixed stuff.  I will attempt to resolve the conflicts ON THE BRANCH.  Fingers crossed.

**Comment by halindrome** [comment]
I am going to throw this away and start over.  Merge conflicts are not cool.

**Pull request closed without merging**
