### PR TITLE
Add blockquote, caption, footer, header, and paragraph roles

### PR DESCRIPTION
**Pull request by joanmarie**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/718.html" title="Last updated on May 1, 2018, 4:38 PM GMT (5e68010)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/718/9e079e3...5e68010.html" title="Last updated on May 1, 2018, 4:38 PM GMT (5e68010)">Diff</a>

### CODE REVIEW

**Comment by prlbr** [comment]
This sentence for role `banner` …

> A region that contains mostly site-oriented content, rather than page-specific content.

… and this sentence for role `header` …

> If the scope of the information is the entire page, authors SHOULD instead use `banner`.

… don’t fit well together. The former says that `banner` is rather not for page-specific content, the latter says that it should be used for page-specific content.

**Comment by carmacleod** [comment]
Probably a typo. The one for header should probably say:

> If the scope of the information is the entire _site_, authors SHOULD instead use banner.

**Comment by carmacleod** [comment]
Probably a typo. The one for `header` should probably say:

> If the scope of the information is the entire _site_, authors SHOULD instead use `banner`.

**Comment by joanmarie** [comment]
Thanks for the feedback on this already-closed pull request (which was closed because we decided to use generic roles for header and footer).

**Comment by carmacleod** [comment]
No problem.  ;)
So are you saying there won't be a new `header` or `footer` role?
What generic role will non-banner headers/footers default to?

**Pull request closed without merging**
