### PR TITLE
Issue 152

### PR DESCRIPTION
**Pull request by cyns**
UIA mappings for footer

### CODE REVIEW

**Comment by stevefaulkner** [comment]
suggest it may be easiest to kill this and do a new pull?

**Comment by jasonkiss** [comment]
I think this is my fault. I went ahead and updated the master branch yesterday to fix issue 152 without noticing this PR.

**Comment by cyns** [comment]
@jasonkiss what do I do to fix this?

**Comment by jasonkiss** [comment]
Both issues for this PR have been closed and the desired changes are in the latest draft. So I've closed this PR. I think you can also go ahead and delete branch for issue-152.

**Pull request closed without merging**
