### PR TITLE
monorepo: add dpub-aam history

### PR DESCRIPTION
**Pull request by pkra**
- [x] fix main on dpub-aam!!!
- [x] add dpub-aam history
- [x] remove extraneous files
- [x] adjust links to aria-common

### CODE REVIEW

**Review by spectranaut — CHANGES_REQUESTED** [review]
@pkra, @daniel-montalvo and I were experimenting in the main branch of dpub-aam.

We are going to have to close this and reopen it when the history over at dpub-aam is restored, to do that we have to drop all the experimental commits on main and force push.

**Comment by pkra** [comment]
DPUB-aam should now be correct again. I'll redo this PR.

**Comment by pkra** [comment]
@spectranaut I've repeated the process on a fresh local branch and forced pushed here. Does this PR look ok to you?

**Comment by spectranaut** [comment]
Looks good!

**Pull request merged**
