### PR TITLE
Update attribute selector reference

### PR DESCRIPTION
**Pull request by MichielBijl**
Fixes issues in https://github.com/w3c/aria/issues/117

### CODE REVIEW

**Comment by Joanmarie** [comment]
I didn't see any reason (or benefit) to have three commits when one is called for. Therefore I manually merged your changes after squashing them. (commit 431fe708a3)

**Comment by MichielBijl** [comment]
No reason, just the way it worked out. I switch a lot between issues/things while I work.

**Comment by Joanmarie** [comment]
Understood. You familiar with the `--amend` option of `git commit`?

**Comment by MichielBijl** [comment]
I thought that was just to edit commit text?

**Comment by Joanmarie** [comment]
Nope. If you make a change and then commit it, go do something else, then come back to the original task and make another change, you can do `git commit -a --amend`. That will add the new changes (assuming they were made to existing files) to the previous commit. It will also give you the opportunity to change the commit message, should you be so moved.

If the duration of the "something else" is significant, you can throw in the `--date` option, e.g. ``git commit -a --amend --date="`date`"`` does what I said above and also updates the timestamp of the commit to the present.

**Comment by MichielBijl** [comment]
Cool! Thank you for the explanation :+1: Will do that next time.

**Comment by Joanmarie** [comment]
Give it a try with issue 121 and let me know if you have any questions/problems. Thanks!

**Pull request closed without merging**
