### PR TITLE
Editorial: fixes minor typos and spelling errors

### PR DESCRIPTION
**Pull request by carmacleod**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/1025.html" title="Last updated on May 7, 2020, 4:27 AM UTC (8e7d74d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1025/690285a...8e7d74d.html" title="Last updated on May 7, 2020, 4:27 AM UTC (8e7d74d)">Diff</a>

### CODE REVIEW

**Comment by carmacleod** [comment]
acessibility -> accessibility
a owned -> an owned
preceeding -> preceding
programatically -> programmatically
a explicit -> an explicit
Content which is important -> Content that is important
a ARIA feature -> an ARIA feature
aria-haspop="true" -> aria-haspopup="true"
manuitemcheckbox -> menuitemcheckbox

**Comment by carmacleod** [comment]
Also, `aria-haspop` was kind of cute.  :)

**Comment by jnurthen** [comment]
If you don't mind I'm going to hold off on merging. Lots of these are in master but not yet merged into stable. As such I'm going to have a hell of a time keeping track of what is merged and what is not in which version of the spec :( 
(unless someone can help me find an easier way to do this....)

**Comment by carmacleod** [comment]
No worries. It will be waiting here until it's convenient.  :)

**Comment by schne324** [comment]
It'd be awesome to use something like [this pull request spell checker thing](https://github.com/chakki-works/typot)

**Comment by jnurthen** [comment]
> It'd be awesome to use something like [this pull request spell checker thing](https://github.com/chakki-works/typot)

Something like it would be good but that only checks README .md and .rst files

**Comment by carmacleod** [comment]
@jnurthen Any chance these old typo fixes can go into 1.2?

**Comment by carmacleod** [comment]
@jnurthen 
Never mind. I don't know why I try to save old branches - it rarely works.
I'm just going to delete this branch and PR and start fresh. Sigh.

**Pull request closed without merging**
