### PR TITLE
prohibit aria-roledescription from role=generic

### LINKED ISSUE #1140: aria-roledescription should not be allowed on role generic
On the call today we decided it was an oversight that `role=generic` will now be allowed to have `aria-roledescription`.

`aria-roledescription` should be prohibited from being used on `role=generic`

### PR DESCRIPTION
**Pull request by scottaohara**
closes #1140, pending answering [comment about note](https://github.com/w3c/aria/issues/1140#issuecomment-568189345)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/1142.html" title="Last updated on Mar 4, 2020, 12:48 AM UTC (5c5bd92)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1142/db5a8c5...5c5bd92.html" title="Last updated on Mar 4, 2020, 12:48 AM UTC (5c5bd92)">Diff</a>

### CODE REVIEW

**Comment by mtrootyy** [comment]
`aria-brailleroledescription` also should be prohibited on role `generic` for the same reason.

**Comment by pkra** [comment]
> `aria-brailleroledescription` also should be prohibited on role `generic` for the same reason.

:+1: (But it's less of a problem since the spec says that UAs must not expose aria-brailleroledescription if there's no valid aria-roledescription.)

**Comment by scottaohara** [comment]
agreed, though still not a bad idea to be explicit :)  making a commit to add this now.

**Comment by jnurthen** [comment]
@scottaohara Can you please remove the commit prohibiting brailleroledescription on generic from this PR. I can't merge that to the 1.2 branch (which is the desire for this) as we won't have brailleroledescription there. We can ask @pkra to add that to #1097

**Comment by scottaohara** [comment]
@jnurthen removed it.

**Comment by carmacleod** [comment]
Or maybe:
> The element to which aria-roledescription is applied has an explicit or implicit WAI-ARIA role that prohibits aria-roledescription.

...and make it the 2nd point?

**Comment by mcking65** [comment]
I think it is important to have this UA restriction language in roledescription before merging:

>The element to which aria-roledescription is applied has an explicit or implicit WAI-ARIA role that prohibits aria-roledescription.

**Comment by jnurthen** [comment]
@scottaohara pushed a change - can you take a look

**Comment by scottaohara** [comment]
i think that looks good, thank you @jnurthen, sorry i didn't get to adding it sooner.

**Pull request merged**
