### PR TITLE
Switch from Travis CI to GitHub action

### PR DESCRIPTION
**Pull request by plehegar**
This removes .travis.yml and install a GitHub action instead.

Using https://github.com/w3c/spec-prod/ instead of using `curl` allows to additional features, such as automatic validation of the document on push and pull requests.

Note that Travis CI has been deactivated for this repository so this needs to get merged asap.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/1504.html" title="Last updated on Aug 6, 2021, 3:20 PM UTC (8feb1c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1504/d494e74...8feb1c8.html" title="Last updated on Aug 6, 2021, 3:20 PM UTC (8feb1c8)">Diff</a>

### CODE REVIEW

**Comment by plehegar** [comment]
spec-prod wasn't able to generate the document, so I switched back to use `curl` again. Note that the account 'w3cbot' in the deploy shell script. You may want to make sure it is authorized to push to this repo or switch to use a different user (the GITHUB_TOKEN is attach to the repo and isn't attached to the user so it will work for any user).

**Comment by plehegar** [comment]
the document needs to be respec happy for this to work. will look.

**Comment by jnurthen** [comment]
@plehegar any updates on this?

**Comment by jnurthen** [comment]
@plehegar any updates?

**Comment by plehegar** [comment]
See #1641

**Pull request closed without merging**
