### PR TITLE
fix: informative references to accname

### PR DESCRIPTION
**Pull request by jnurthen**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/1810.html" title="Last updated on Sep 19, 2022, 9:43 PM UTC (a0b6db6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1810/bcf44d1...a0b6db6.html" title="Last updated on Sep 19, 2022, 9:43 PM UTC (a0b6db6)">Diff</a>

### CODE REVIEW

**Comment by jnurthen** [comment]
fixes #1792

**Review by pkra — APPROVED** [review]

**Comment by pkra** [comment]
I'm wondering what the right reference would be to learn about magical respec incantations (to add to the readme or the on boarding wiki page).

**Comment by jnurthen** [comment]
> I'm wondering what the right reference would be to learn about magical respec incantations (to add to the readme or the on boarding wiki page).

unless we write something the best is the respec doc (respec.org) but it has far more than we use. I really need to go through https://github.com/w3c/aria#editorial-documentation and update based on current usage (but it will never be fully comprehensive)

**Comment by pkra** [comment]
Sounds good -- thanks for opening https://github.com/w3c/aria/issues/1813

**Pull request merged**
