### PR TITLE
aria-atomic has no default

### PR DESCRIPTION
**Pull request by annevk**
Its computed value depends on its ancestors.

# PR tracking
Check these when the relevant issue or PR has been made, OR after you have confirmed the
related change is not necessary (add N/A). Leave unchecked if you are unsure. Read the
[Process Document](https://github.com/w3c/aria/wiki/ARIA-WG-Process-Document/_edit) or
[Test Overview](https://github.com/w3c/aria/wiki/ARIA-Test-Overview) for more information.

* [ ] Related Core AAM Issue/PR:
* [ ] Related AccName Issue/PR:
* [ ] Related APG Issue/PR:
* [ ] Any other dependent changes?

# Implementation tracking

* [ ] "author MUST" tests:
* [ ] "user agent MUST" tests:
* [ ] Browser implementations (link to issue or when done, link to commit):
   * WebKit:
   * Gecko:
   * Blink:
* [ ] Does this need AT implementations?

***
<a href="https://pr-preview.s3.amazonaws.com/annevk/aria/pull/1894.html" title="Last updated on Mar 23, 2023, 10:49 AM UTC (b9e3131)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1894/9033f63...annevk:b9e3131.html" title="Last updated on Mar 23, 2023, 10:49 AM UTC (b9e3131)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
I had a discussion with @cookiecrook about cases like this and what I think we want to do is distinguish between the DOM attribute and the AT property. Also to make it clear what computations are owned by the AT.

The DOM attribute is "true" or "false", invalid, or missing.

The AT property depends on the DOM attribute, the computed role, ancestor elements, etc.

I will take a stab at demonstrating what that would mean for the specification tomorrow by creating a draft PR for a single property.

**Comment by spectranaut** [comment]
Just to be clear, this proposed change is editorial, correct? This is related to this re-thinking of the "default value" in https://github.com/w3c/aria/pull/1896 but we aren't changing anything normative about the spec, or any behavior of the browser?

**Review by cookiecrook — APPROVED** [review]

**Comment by annevk** [comment]
I'm not sure it's editorial (it's not a typo fix and arguably fixes an error), but it shouldn't have normative impact.

> with this change, should we also not change or removing the word "default" in the following sentence:

Reworking that would be a larger change we'd make as part of what #1896 illustrates.

All this is making clear is that it doesn't have an intrinsic default. You need to read the prose to determine the default.

**Comment by cookiecrook** [comment]
@jnurthen @spectranaut Can this be merged? As @annevk said, it's not technically "editorial", but it's clearly "errata" IMO.

**Review by jnurthen — APPROVED** [review]

**Pull request merged**
