### PR TITLE
Editorial: Clarify the use of "undefined" as a literal value in the ARIA spec

### PR DESCRIPTION
**Pull request by joanmarie**

### CODE REVIEW

**Comment by joanmarie** [comment]
@richschwer and @michael-n-cooper: I believe these changes are editorial and improve the situation regarding the use of "undefined" as a literal value. Please review. Thanks!

**Comment by richschwer** [comment]
These changes are fine.

**Comment by joanmarie** [comment]
Thanks @richschwer. I have merged 8f8559d (the first of two commits in this pull request). As per @michael-n-cooper's suggestion, I am going to hold off on merging the second commit (982ed36) until I've explicitly pinged the list. (I already mentioned the proposed changes in the context of the thread on aria-current, but we should ensure everyone has seen it.)

**Comment by joanmarie** [comment]
Since there was no negative feedback regarding the proposed changes in the second commit, I've just merged those into master.

**Pull request closed without merging**
