### PR TITLE
A11ydoer-patch- menubuttonexlink

### PR DESCRIPTION
**Pull request by a11ydoer**
updating menu button role example link in the aria-practices.html

### CODE REVIEW

**Comment by a11ydoer** [comment]
I don't know why my pull request has other commits by @michael-n-cooper.
@jnurthen let me know whether this pull request works or not.

**Comment by MichielBijl** [comment]
There seems to be something messing something up. I'm closing this because we can't merge this.

Can you check if you have the latest version of master locally? You can check by checkout out the master branch, and then performing a pull. On the command line, this would be done by:

```
git checkout master
git pull
```

If you need any help, please let me know. If you want, I can make the change for you (just tell me what needs to be changed).

**Comment by a11ydoer** [comment]
I did clean check out twice but still the same. Can you check Michale Cooper's answer?

**Comment by MichielBijl** [comment]
Which answer is that?

**Comment by MichielBijl** [comment]
I've taken the liberty to fix this directly in master: https://github.com/w3c/aria/commit/62154b86804d805955ebe5c4d836d04ef8325008

**Pull request closed without merging**
