### PR TITLE
adding menu button example file

### PR DESCRIPTION
**Pull request by a11ydoer**
adding menu button example file. css, js and html files

### CODE REVIEW

**Comment by MichielBijl** [comment]
Can you explain why all links to the APG point to TR (like `https://www.w3.org/TR/wai-aria-practices-1.1/#h-button`)?

Other than that, it looks good.

**Comment by a11ydoer** [comment]
can you change the link to relative and correct path?

**Comment by MichielBijl** [comment]
I don't have access to your branch/repository; so I can't :)

**Comment by a11ydoer** [comment]
I checked my branch, (a11ydoer:a11ydoer-patch-menu) and it shows the correct and relative path,  <p><a href="../../aria-practices.html#h-menubutton">Authoring Practice Design Patten for Menu Button</a></p> it is weird. By the way, I thought you have a write access(edit the file directly on github) to march heartbeat branch, don't you?

**Comment by MichielBijl** [comment]
I do have access to the ARIA repo, but not your patch version—that is under your account—; so I can't fix it in this pull request.

**Comment by a11ydoer** [comment]
my commit shows correct link. (Am I looking at wrong branch?) can you check one more time whether it is not the correct link?

**Comment by a11ydoer** [comment]
you can look at my branch.
`https://github.com/a11ydoer/aria/blob/a11ydoer-patch-menu/practices/examples/menu-button/menu-button-1.html`

It shows correct link.

**Comment by MichielBijl** [comment]
That is weird, if you look in the “files changed” tab of this pull request, it shows a different URL :/

**Comment by a11ydoer** [comment]
oh. I know what happened. Before I got your answer about spec link, whether it should be relative or absolute path - I have already changed them to absolute path and created a pull request. When I created pull request for menu button example today, previous pull requests were added to the same branch. Now I reverted back spec links to relative links. 
Please review one more time and merge the changes. Thanks, Michiel!

**Comment by MichielBijl** [comment]
Ah, that's better! As discussed during yesterday's call; @michael-n-cooper should review this and merge it :) Thanks Jemma!

**Comment by jnurthen** [comment]
Can you confirm the only files which should be touched by this PR are the files in the menu-button directory. All the other files should be untouched?

**Comment by a11ydoer** [comment]
@jnurthen Please mention my name with @ in the comment if you need my attention for the menu-button   merge.

**Comment by jnurthen** [comment]
sorry @a11ydoer Yes I need your attention.
I'm unsure which files should be touched by this. Merging into master is a somewhat manual process. It looks like the only files which should have been touched are the menu-button directory files.
If that is correct please close this PR and create a new one based on master this time which contains only these changes.

**Pull request closed without merging**
