### PR TITLE
Move focus-change-request content from Core-AAM to ARIA

### PR DESCRIPTION
**Pull request by joanmarie**
This content is not platform-specific and is similar in nature to
the other managing-focus content in the ARIA spec.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/840.html" title="Last updated on Nov 8, 2018, 3:36 PM GMT (0dc6e58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/840/0ce46ea...0dc6e58.html" title="Last updated on Nov 8, 2018, 3:36 PM GMT (0dc6e58)">Diff</a>

### CODE REVIEW

**Comment by joanmarie** [comment]
@jnurthen please review. Thanks!

**Comment by joanmarie** [comment]
@jnurthen: I went to cherry-pick this into stable and discovered that none of the "Managing focus and supporting keyboard navigation" changes were in stable yet. Please remind me if we decided to hold off on merging that content. (I thought one of us was going to cherry-pick it.)

**Comment by jnurthen** [comment]
@joanmarie I don't see any reason we wouldn't cherry-pick #801 into stable. This was one we did on that Wednesday at TPAC so I'm guessing that is why it slipped.

**Comment by joanmarie** [comment]
@jnurthen: Oh yeah. TPAC brain fog. Thanks for the reminder. I've cherry-picked it and subsequently cherry-picked the change in this pull request.

**Pull request merged**
