### PR TITLE
Core-AAM: Add macOS mapping for aria-errormessage

### PR DESCRIPTION
**Pull request by joanmarie**
Expose the textual content of the referenced element as the value of
AXHelp.

Fixes github issue #457.

### CODE REVIEW

**Comment by joanmarie** [comment]
@cookiecrook: Please review. Thanks!

**Comment by cookiecrook** [comment]
We usually don't recommend putting any critical information in AXHelp, since a lot of users will disable VoiceOver speaking help text until a command is issued. I think our options are:

- Append it to the label,
- Trigger an announcement at the time it is shown, or
- Expose it as a new TBD API.

**Comment by stes-acc** [comment]
>>>>  … since a lot of users will disable VoiceOver speaking help text until a command is issued.

Is there a specific key or/and gesture to speak AXHelp on request for a given control?


-          Stefan

**Comment by joanmarie** [comment]
> We usually don't recommend putting any critical information in AXHelp, since a lot of users will disable VoiceOver speaking help text until a command is issued. I think our options are:
> * Append it to the label,
> * Trigger an announcement at the time it is shown, or
> * Expose it as a new TBD API.

Fair enough. Thanks for the review!

Unfortunately, the lack of mapping is one of the things blocking the Core AAM from being able to enter CR. We **_really, really, really_** need to know what your platform's mapping is. Patches not only "welcome", but strongly encouraged. :smile:

**Comment by cookiecrook** [comment]
@stes-acc wrote:

> Is there a specific key or/and gesture to speak AXHelp on request for a given control?

VO+Cmd+H will speak it on demand. Optionally, but by default, it will be spoken after a user-adjustable-length pause.

**Comment by joanmarie** [comment]
> Works for me, but I added the last commits, so maybe you should review.

Thanks! What you did works for me. But I couldn't be bothered to figure out how to use github's UI to change authorship as part of a squash and merge, so I just did it the old-fashioned way. :smile:. a314c09.

Thanks again!

**Pull request closed without merging**
