### PR TITLE
Master

### PR DESCRIPTION
**Pull request by a11ydoer**
added mixed state checkbox example and coding template for review

### CODE REVIEW

**Comment by a11ydoer** [comment]
This code will be revised with html5 fieldset/label information for group checkbox based upon ARIA-APG group's recommendation. I will create new pull request with revised code at the end of this week.

**Comment by MichielBijl** [comment]
What is the progress on this?

**Comment by a11ydoer** [comment]
I will create a pull request with most up to date mixed checkbox code today.

**Comment by a11ydoer** [comment]
This will be the code to be committed. 
https://github.com/a11ydoer/practices/blob/master/examples/checkbox/checkbox-3.html

**Comment by MichielBijl** [comment]
Looks good to me :+1:

**Pull request merged**
