### PR TITLE
Aria graphics: changes to role descriptions

### PR DESCRIPTION
**Pull request by AmeliaBR**
Attn @richschwer @chaals 

Please pull this in as a separate branch so that other members of the SVG Accessibility task force can edit.  I made some significant changes we haven't discussed yet, so we probably don't want to merge it into the master just yet.

I'll send an email to the list explaining the changes in detail.

### CODE REVIEW

**Comment by chaals** [comment]
Given that the master branch had almost no content before, and is a rough draft, I think it is reasonable to pull this straight in…

**Comment by AmeliaBR** [comment]
@chaals 

That's fine too.  It depends on how much work Rich is doing with the introductory sections.  If he's already started, it might be easier to wait and run the merge once.

**Comment by LjWatson** [comment]
@AmeliaBR 
Merged with thanks.

It doesn't look like you've changed the intro. If 
@richschwer
 is working on that, he should be able to pull down your commits from the master without overwriting his local changes. If that isn't the case, Github
will notify us if any conflicts need to be resolved.

I'm also not sure it's possible to create a new branch from a PR. I *think the branch needs to be created, forked locally and for the PR to be issued against
the branch.

**Comment by AmeliaBR** [comment]
Thanks Léonie.  & thanks also for the tips.  As you say, probably won't be a problem this time, but good to know for the future.

**Pull request merged**
