### PR TITLE
Remove default value for aria-expanded from combobox role

### PR DESCRIPTION
**Pull request by melanierichards**
Addresses #853

### CODE REVIEW

**Comment by jnurthen** [comment]
[link for review](https://raw.githack.com/melanierichards/aria/combobox-default/index.html#combobox)

**Comment by jnurthen** [comment]
Need to remove 

> Elements with the role combobox have an implicit aria-expanded value of false.

**Comment by carmacleod** [comment]
Also, consider changing:
> Typically, the default state of a combobox is collapsed.

to:
> Typically, the initial state of a combobox is collapsed.

**Comment by melanierichards** [comment]
Updated per @jnurthen and @carmacleod's feedback!

**Pull request merged**
