### PR TITLE
Remove implicit value of aria-level from heading role

### PR DESCRIPTION
**Pull request by melanierichards**
Addresses issue #854

***
<a href="https://pr-preview.s3.amazonaws.com/melanierichards/aria/pull/942.html" title="Last updated on Apr 25, 2019, 3:57 AM UTC (490eb68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/942/78b9178...melanierichards:490eb68.html" title="Last updated on Apr 25, 2019, 3:57 AM UTC (490eb68)">Diff</a>

### CODE REVIEW

**Comment by jnurthen** [comment]
[link for review](https://raw.githack.com/melanierichards/aria/heading-default/index.html#heading)

**Comment by jnurthen** [comment]
I think 

> If headings are organized into a logical outline, the aria-level attribute is used to indicate the nesting level.
needs rewording now that aria-level is required.

**Comment by carmacleod** [comment]
Something like:
> Headings SHOULD be organized into a logical outline, and the aria-level attribute MUST be used to indicate the nesting level.

?

**Comment by melanierichards** [comment]
@jnurthen @carmacleod 

In the spirit of simplifying shoulds/musts, how about:

> To ensure headings are organized into a logical outline, authors MUST use the `aria-level` attribute to indicate the proper nesting level.

**Comment by melanierichards** [comment]
Made the suggested change!

**Comment by accdc** [comment]
As a quick question about the accessibility tree mappings, what heading level will a heading have if there is no implicit level?
Thanks, Bryan

**Comment by jnurthen** [comment]
> As a quick question about the accessibility tree mappings, what heading level will a heading have if there is no implicit level?
> Thanks, Bryan

http://w3c.github.io/aria/#document-handling_author-errors_states-properties states

> If a required WAI-ARIA attribute for a given role is missing, user agents SHOULD process the attribute as if the values given in the following table were provided.
 In the table the fallback for aria-level is 2

So not supplying a heading level is now an author error, but if a browser is following the fallback guidance it should still expose it with a level of 2.

**Comment by accdc** [comment]
Excellent, thanks, that was my only concern with this.

**Pull request merged**
