### PR TITLE
Add a conditional on when aria-controls is needed

### LINKED ISSUE #1334: Combobox shouldn't need aria-controls until the popup is rendered
Combobox states
“Authors MUST set aria-controls on a combobox element to a value that refers to the combobox popup element.”

This only needs to be true once the popup has rendered. Until that time the idref is unknown.

### PR DESCRIPTION
**Pull request by jnurthen**
resolves #1334

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/1335.html" title="Last updated on Nov 20, 2020, 12:30 AM UTC (eef2e15)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/1335/19e5b99...eef2e15.html" title="Last updated on Nov 20, 2020, 12:30 AM UTC (eef2e15)">Diff</a>

### CODE REVIEW

**Comment by carmacleod** [comment]
Does it make sense to add an Implied

**Review by carmacleod — APPROVED** [review]
Approving as-is, but would like an answer on whether or not adding Implicit value for role makes sense (or would just add more confusion).
Thanks @jnurthen !

**Comment by jnurthen** [comment]
Yeah - we nee

> Approving as-is, but would like an answer on whether or not adding Implicit value for role makes sense (or would just add more confusion).
> Thanks @jnurthen !

We have to do something - either add an implicit value or move to supported... Lets add to today's agenda and see what others think.

**Review by mcking65 — CHANGES_REQUESTED** [review]
This PR makes it more clear that aria-controls needs to be supported not required. If it is not present when the combobox is collapsed, the combobox would not validate.

**Comment by carmacleod** [comment]
+1 for the new state of this PR, which does 2 things:
- Adds "When the popup is displayed," so that the requirement for authors says the following:
  > When the popup is displayed, authors MUST set aria-controls on a combobox element to a value that refers to the combobox popup element.
- Moves aria-controls from required to supported in the characteristics table.

**Review by MelSumner — APPROVED** [review]
👍

**Review by mcking65 — APPROVED** [review]
Looks great!

**Pull request merged**
