### PR TITLE
Move Aria Orientation on scrollbar to supported section (from required)

### PR DESCRIPTION
**Pull request by jnurthen**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria/pull/781.html" title="Last updated on Jun 6, 2018, 7:53 PM GMT (d9e9ae2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria/781/f048989...d9e9ae2.html" title="Last updated on Jun 6, 2018, 7:53 PM GMT (d9e9ae2)">Diff</a>

### CODE REVIEW

**Comment by jnurthen** [comment]
When merged will fix #780

**Comment by joanmarie** [comment]
Maybe I'm tired, but I'm not seeing where I can explicitly review this. That said, I disagree with the change as indicated in #780. Please explain why we want to make aria-orientation a non-required property.

**Comment by joanmarie** [comment]
BTW, nit: We have historically (and imho want to continue to) add ChangeLog entries with the most recent at the top. I hadn't noticed that this didn't occur with the IDL / reflection merge. So once we determine what changes we want to make to fix the issue associated with the pull request, mind also moving the changelog entries so that the most recent are at the top? Thanks!

**Comment by jnurthen** [comment]
This is superseded by #858

**Pull request closed without merging**
