### PR TITLE
Required properties missing

### PR DESCRIPTION
**Pull request by halindrome**
Thanks @Joanmarie for running this down.  I think it is fine to merge.  I will need to update ariaChild.js too, but can do that separately.

### CODE REVIEW

**Comment by halindrome** [comment]
I don't want to perturb anything but I think this is an important fix.  @cookiecrook can you take a look and see if you are okay with it?

**Comment by halindrome** [comment]
My checkin message was unclear there.  I incorporated her changes into ariaChild.js

**Comment by halindrome** [comment]
As per PFWG meeting today, merging this.  I will then update roleInfo.js from the latest aria spec in the trunk and push that so it is available for DPUB.

**Comment by cookiecrook** [comment]
@halindrome wrote:

> I don't want to perturb anything but I think this is an important fix. @cookiecrook can you take a look and see if you are okay with it?

Sorry, I've been to busy to review this. I have complete faith in the two of you. ;-)

**Pull request merged**
