### PR TITLE
ARIA 1.2: Add explicit guidance for non-pertinent errormessage elements (#587)

### PR DESCRIPTION
**Pull request by joanmarie**
* When aria-errormessage is not pertinent, authors MUST either ensure
  the content is not rendered or remove the aria-errormessage attribute
  or its value.

* User agents MUST NOT expose an element as a pertinent error message
  when the referencing element lacks aria-invalid set to true.

### CODE REVIEW

**Comment by joanmarie** [comment]
Spec-view: https://rawgit.com/w3c/aria/issue-587/aria/aria.html#aria-errormessage

**Comment by joanmarie** [comment]
@richschwer and @mcking65, please review. Once we have consensus on the wording, I'll ping Mozilla and Google (since they've already implemented support) to do the same. Thanks!

**Comment by joanmarie** [comment]
Thanks Matt.  I've merged your changes into this branch. Anything else needed?

**Comment by mcking65** [comment]
@joanmarie, I gave it another read through; With the pull #590 merge, I think it is good to go.

**Comment by joanmarie** [comment]
@asurkov and @minorninth: thoughts on this change? As far as user agents implementing support goes, it should boil down to the addition of a single sanity check:

> User agents MUST NOT expose aria-errormessage for an object when the object lacks aria-invalid set to true.

The benefit is that every single assistive technology doesn't have to do that same sanity check: If an error message is exposed by the user agent, by definition it is relevant/pertinent to the user.

**Comment by minorninth** [comment]
Sounds good to me except that I think any non-false value for aria-invalid should be counted as "true", and  as currently worded it's a bit unclear what to do with aria-invalid=spelling or grammar or any future allowed enum value.

**Comment by joanmarie** [comment]
> Sounds good to me except that I think any non-false value for aria-invalid should be counted as "true", and as currently worded it's a bit unclear what to do with aria-invalid=spelling or grammar or any future allowed enum value.

Argh. Good point. Thanks!!

**Comment by joanmarie** [comment]
New language is:

> User agents MUST NOT expose `aria-errormessage` for an object with an `aria-invalid` value of `false`.

**Comment by asurkov** [comment]
The behavior may be obscure for the authors or testing, when they have aria-invalid=false on an element for any reason, otherwise the change looks reasonable, especially if it makes AT life easier.

**Comment by mcking65** [comment]
@joanmarie, I agree with the recent change to ensure that all ways of creating  a false value for aria-invalid are covered.

**Comment by joanmarie** [comment]
The working group concluded that this could wait until 1.2. I'll merge after we branch.

**Pull request merged**
