### PR TITLE
"accessible" -> "accessible object" where appropriate

### PR DESCRIPTION
**Pull request by jasonkiss**
Fixed two instances where "accessible" was used to mean "accessible object"

### CODE REVIEW

**Comment by MichielBijl** [comment]
Looks good to me :+1:

**Comment by klown** [comment]
Thanks Jason
Now waiting on @cyns modifications to the UIA example.

**Comment by klown** [comment]
@jasonkiss, I've merged your changes.  Please take a look and confirm it's all there.  I had to resolve conflicts during the merge and something may have gone awry.  I checked, and it looks okay to me, but a second pair of eyes would be good.
Thanks!

**Comment by jasonkiss** [comment]
LGTM 2. Thanks, @klown.

**Comment by klown** [comment]
Thanks @jasonkiss.  I'll close this then.

**Pull request closed without merging**
