### PR TITLE
Updated aria examples, banner and contenting

### PR DESCRIPTION
**Pull request by jongund**
Added updated versions of examples, still need to do some linking to the practices, also update banner and contenting

### CODE REVIEW

**Comment by joanmarie** [comment]
Since the aria-practices.html file was moved to a dedicated repo, this pull request needs to be moved/redone/whatever. I'm keeping this open for now, so we don't lose Jon's proposed changes. But it would be great if someone could ensure it's moved to the practices repo and then close out this pr. Thanks!

**Comment by brentonstrine** [comment]
Where does that dedicated repo live?

**Comment by joanmarie** [comment]
As stated in the [practices/README.md](https://github.com/w3c/aria/blob/master/practices/README.md) and in the conflicting file ([practices/aria-practices.html](https://github.com/w3c/aria/blob/master/practices/aria-practices.html)):

> https://github.com/w3c/aria-practices/

**Comment by joanmarie** [comment]
I'm closing this to get it off our open PR list. If the changes still need to be made, please open a new PR against the new repo (https://github.com/w3c/aria-practices/).

**Pull request closed without merging**
